### ISSUE TITLE
关于待处理程序中的数字字面量

### ISSUE THREAD

**Issue by swkfk** [OnlyAR/2024-ds-project#1]
诸如 `0x12341234` `1e8` `0.33f` `12345667889034L` 都属于应该保留在关键信息流中的内容，而不可直接将其中的 `x e f L` 等字母视作变量。

**但是！虽然测试数据中存在这样的数据，但是保证不影响结果。**

可以通过 Readme 或者 Issue 说明具体情况，以免考虑了这些情况的同学陷入困境。

**Comment by OnlyAR** [comment]
收到！
